# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('probe', models.CharField(default=None, max_length=8)),
                ('type', models.CharField(choices=[('TI', 'Internal Temperature'), ('TE', 'External Temperature'), ('R', 'Resistance')], max_length=2)),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'data',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
            ],
        ),
        migrations.AddField(
            model_name='datum',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbq_thermometer.Session'),
        ),
    ]
